okta:
  oauth2:
    issuer: https://dev-org1gkrj5i6kdrdr.us.auth0.com/
    client-id: YJmn8m8hXZkTEr5kSIjZGIkIHkPBU3Li
    client-secret: I8Vozq8EU9oOTif2HMucFj6A-9YwVVbuk8TCgqV7kQg1rc_CnchGt_il4MdOjQNM

resend:
  api-key: re_LXf4WeDe_4ZAvCYKD7CnkPYPF5sbQHmPg

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-org1gkrj5i6kdrdr.us.auth0.com/